version: "3.8"
services:
  mongodb:
    #    container_name: "mongodb"
    #    networks:
    #      - notes-net
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./config/development.env
  frontend:
    build: ./client
    image: "notes-frontend"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/src:/app/src
  backend:
    #    networks:
    #      - notes-net
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "notes-backend"
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./config/development.env
volumes:
  mongo-data:
    external: true